# .github/workflows/frontend-ci.yml
name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: npm run lint || true
      continue-on-error: true
    
    - name: Type check
      run: npm run type-check || npx tsc --noEmit
      continue-on-error: true
    
    - name: Run tests
      run: npm test -- --coverage --watchAll=false || true
      continue-on-error: true
    
    - name: Build project
      run: npm run build
      env:
        CI: true
        REACT_APP_API_URL: http://localhost:8000' 
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build
        path: frontend/build
        retention-days: 7
    
    - name: Check bundle size
      run: |
        echo "Build size report:"
        du -sh build/static/js/*.js || true
        du -sh build/static/css/*.css || true